name: Lint & Unit Test
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
      - name: Run Lint
        run: npm run lint
      - name: Run tests
        run: npm run test
